#!/bin/sh
ctanify tikzscale.ins tikzscale.pdf README test-tikzscale.tex test-tikzscale.pdf pgfplots.randn.dat=doc/latex/tikzscale "*.tikz=doc/latex/tikzscale" test-tikzscale.tex=doc/latex/tikzscale beamer/*.tex=doc/latex/tikzscale beamer/*.tikz=doc/latex/tikzscale
