#!/bin/sh
ctanify tikzscale.ins tikzscale.pdf README test-tikzscale.tex test-tikzscale.pdf testRectangle.tikz testgraphic2D.tikz linewidth.tikz pgfplots-test.tikz  "*.tikz=doc/latex/tikzscale" test-tikzscale.tex=doc/latex/tikzscale
